// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Action = { "type": "keyPress", key: string, } | { "type": "keyCombination", keys: Array<string>, } | { "type": "mouseMoveDirection", direction: Direction, distance: number, } | { "type": "mouseClick", mouse_button: MouseButton, } | { "type": "mouseMoveStick", mouse_mode: MouseMoveMode, } | { "type": "scrollDirection", direction: Direction, distance: number, } | { "type": "scrollStick" } | { "type": "setMouseSensitivity", sensitivity: number, } | { "type": "increaseMouseSensitivity", amount: number, } | { "type": "decreaseMouseSensitivity", amount: number, } | { "type": "resetMouseSensitivity" };

export type Direction = "up" | "down" | "left" | "right" | "upLeft" | "upRight" | "downLeft" | "downRight";

export type MouseButton = "left" | "right" | "middle";

export type MouseMoveMode = "relative" | "absolute";
