// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mapping } from "./mapping";

export type Config = { startOnBoot: boolean, mappings: Array<Mapping>, mouseSensitivity: number, scrollDistance: number, deadzone: number, };
