// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mapping } from "./mapping";

export type Config = { mappingActiveOnBoot: boolean, mappings: Array<Mapping>, deadzone: number, keyboardLayout: string | null, };
