// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GamepadAxis = "leftX" | "leftY" | "rightX" | "rightY" | "triggerLeft" | "triggerRight";

export type GamepadButton = "a" | "b" | "x" | "y" | "back" | "guide" | "start" | "leftStick" | "rightStick" | "leftShoulder" | "rightShoulder" | "dPadUp" | "dPadDown" | "dPadLeft" | "dPadRight" | "misc1" | "paddle1" | "paddle2" | "paddle3" | "paddle4" | "touchpad";

export type GamepadState = { id: number, name: string, buttons: Record<GamepadButton, boolean>, axis: Record<GamepadAxis, number>, };
